### ISSUE TITLE
Issue while upgrading from E16

### ISSUE THREAD

**Issue by shameerariff** [batden/git-enlightened#2]
The latest available version of this script is 16.7
[You are currently using v16.7]

SCANNING SYSTEM AND GIT REPOSITORIES... 

Ubuntu Zesty... OK 

 ANOTHER VERSION OF ENLIGHTENMENT IS INSTALLED. 
 SCRIPT ABORTED. 
Can you kindly help me out.
The OS is ubuntu 16.10

**Comment by batden** [comment]
Hi shameerariff,
Enlightenment 17 is a complete rewrite of E16. E is now based on the Enlightenment Foundation Libraries (aka EFL). Despite sharing a common name, E16 (still under development today) and E17 (E22 is the most recent version of the modern E desktop environment) are completely different beasts.
There is no way to upgrade from E16 to E17-E22!
